version: '3'
services:
  app:
    build: .
    container_name: spendesk_app
    depends_on:
      - postgres
    environment:
      NODE_ENV: development
      PORT: 3000
      DATABASE_HOST_DOCKER: ${DATABASE_HOST}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
    volumes:
      - .:/app/
      - /app/node_modules
    ports:
      - "3000:3000"
    command: npm run dev
    networks:
      - spendesk-network
  postgres:
    image: postgres:12
    container_name: ${DATABASE_CONTAINER}
    env_file:
      - .env
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
#      POSTGRES_DATABASE: ${DATABASE_NAME}
#      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - ./tools/data/dev:/var/lib/postgresql/data/ # persist data even if container shuts down
    networks:
      - spendesk-network
networks:
  spendesk-network:
    driver: "bridge"